name: Download APK from APKCube

on:
  workflow_dispatch: 

jobs:
  download-job:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # שונה מ-v3 ל-v4

    - name: Setup Node.js
      uses: actions/setup-node@v4 # שונה מ-v3 ל-v4
      with:
        node-version: '20' # עדכנתי לגרסת נוד עדכנית יותר

    - name: Install dependencies
      run: |
        npm init -y
        npm install playwright playwright-extra puppeteer-extra-plugin-stealth
        npx playwright install chromium

    - name: Run Downloader Script
      run: node scraper.js 

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4 # שונה מ-v3 ל-v4 שזה מה שגרם לשגיאה
      with:
        name: Downloaded-APK
        path: ./*.apk
